package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

func main() {
	commit := git("rev-parse", "--short=8", "HEAD")
	if commit == "" {
		commit = "unknown"
	}
	dirty := git("status", "--porcelain") != ""
	content := fmt.Sprintf("// Code generated by go generate ./internal/version; DO NOT EDIT.\npackage version\n\nconst generatedCommit = %q\nconst generatedDirty = %t\n", commit, dirty)
	if err := os.WriteFile("generated.go", []byte(content), 0644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func git(args ...string) string {
	cmd := exec.Command("git", args...)
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}
